version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://admin:hypergro@mongo:27017/
    volumes:
      - .:/app

      
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: hypergro
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: hypergro
      ME_CONFIG_MONGODB_URL: mongodb://admin:hypergro@mongo:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: hypergro

volumes:
  mongo:
  redis_data:
  air_tmp:
